services:
  - type: web
    name: backend-service
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
  - type: web
    name: nlp-service
    env: python3
    buildCommand: cd NLP && pip install -r requirements.txt
    startCommand: cd NLP && python main.py
  - type: static
    name: frontend-service
    buildCommand: cd vite-project && npm install && npm run build
    publishDir: vite-project/dist